spring:
  application:
    name: Noshow_blue_2025

  datasource:
    url: jdbc:mysql://localhost:3306/Noshow2025?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: Noshow2025
    password: 2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
jpa:
    hibernate:
      ddl-auto: update  # Entity 기반으로 table 생성
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
jwt:
  secret: VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1leGFtcGxlLWtleS1mb3ItSlc=


server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:www.noshow2025.shop.pfx
    key-store-type: PKCS12
    key-store-password: 2025
    client-auth: none
