spring:
  application:
    name: Noshow_blue_2025

  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=Asia/Seoul&characterEncoding=UTF-8  # MySQL 데이터베이스 URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: noshow
    password: 2025

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update  # 스키마 자동 생성 (운영 환경에서는 'none' 권장)
      properties:
        hibernate:
          format_sql: true  # SQL 보기 좋게 출력
          show_sql: true  # SQL 출력

    sql:
      init:
        mode: always  # 애플리케이션 시작 시 SQL 스크립트 실행 (필요한 경우)

server:
  address: 172.21.103.108
  port: 443
  ssl:
    enabled: true
    key-store: classpath:noshow2025.shop.pfx
    key-store-type: PKCS12
    key-store-password: 2025
    client-auth: need